
UPDATE sector_zones SET name_fr='300' WHERE name='300' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Adl' WHERE name='Adl' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='bvcbbc' WHERE name='bvcbbc' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Chateux' WHERE name='Chateux' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Lhm' WHERE name='Lhm' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Stad' WHERE name='Stad' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Tst 1' WHERE name='Tst 1' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Zaghlouk' WHERE name='Zaghlouk' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Zaghloul' WHERE name='Zaghloul' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='El Istiqlal' WHERE name='الاستقلال' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='El Hachem' WHERE name='الحشم' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Erradar' WHERE name='الردار' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='El Hach' WHERE name='الهش' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Ouled Hammou' WHERE name='اولاد حمو' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Bouski' WHERE name='بوسكي' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Bouguirat' WHERE name='بوڨيراط' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Tijdit' WHERE name='تجديت' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Hay Salamandre' WHERE name='حي سلمندر' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Daira Mostaganem' WHERE name='دائرة مستغانم' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Debdaba' WHERE name='دبدابة' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Doukara' WHERE name='دوكارة' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sanjul' WHERE name='سانجول' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Stidia' WHERE name='ستيدية' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Souaflia' WHERE name='سوافلية' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Souika' WHERE name='سويقة' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sidi Ali' WHERE name='سيدي علي' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sidi Falag' WHERE name='سيدي فلاڤ' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sidi Falag' WHERE name='سيدي فلاق' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sidi Lakhdar' WHERE name='سيدي لخضر' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sidi Ladjel' WHERE name='سيدي لعجال' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sirat' WHERE name='سيرات' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Cheraifia' WHERE name='شرايفية' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Salamandre' WHERE name='صلامندر' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Sour' WHERE name='صور' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Touahria' WHERE name='طواهرية' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Aizeb' WHERE name='عيزب' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Ain Tedles' WHERE name='عين تادلس' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Ain Nouissy' WHERE name='عين نويصي' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Fornaka' WHERE name='فرناكة' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Kaddadra' WHERE name='قدادرة' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Castor' WHERE name='كاستور' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Lanfayel' WHERE name='لانفاىل' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Linas' WHERE name='ليناس' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Massra' WHERE name='ماسرة' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Mamache' WHERE name='ماماش' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Medjdoub' WHERE name='مجدوب' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Mazaghran' WHERE name='مزغران' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Mansoura' WHERE name='منصورة' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Mouchti' WHERE name='موشتي' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Montplaisir' WHERE name='مونبليزير' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Oued El Kheir' WHERE name='واد الخير' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Ouled Bachir' WHERE name='ولاد بشير' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Willis' WHERE name='ويليس' AND name_fr IS NULL;
UPDATE sector_zones SET name_fr='Yenaro' WHERE name='ينارو' AND name_fr IS NULL;
